"""Add auth fields

Revision ID: 12bac7852fc7
Revises: 563734aa12e8
Create Date: 2026-02-16 21:07:25.428643

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12bac7852fc7'
down_revision = '563734aa12e8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Apply the upgrade migrations."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('activation_token', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('reset_password_token', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('reset_password_token_expires_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the upgrade migrations."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'reset_password_token_expires_at')
    op.drop_column('users', 'reset_password_token')
    op.drop_column('users', 'activation_token')
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###
