"""initial

Revision ID: 20251130_initial
Revises: 
Create Date: 2025-11-30 11:45:23.847288

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20251130_initial'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Apply the upgrade migrations."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('families',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('priority', sa.Integer(), server_default='5', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_families_name'), 'families', ['name'], unique=True)
    op.create_table('functions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_functions_name'), 'functions', ['name'], unique=True)
    op.create_table('projects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('google_drive_folder', sa.String(length=255), nullable=True),
    sa.Column('quote', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_code'), 'projects', ['code'], unique=False)
    op.create_index(op.f('ix_projects_deleted_at'), 'projects', ['deleted_at'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('admin', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('contract', sa.Enum('Intern', 'Flex', 'ZZP', name='contract_type'), nullable=True),
    sa.Column('experience_bat', sa.Enum('Nieuw', 'Junior', 'Medior', 'Senior', name='experience_bat_type'), nullable=True),
    sa.Column('smp_huismus', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('smp_vleermuis', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('smp_gierzwaluw', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('pad', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('langoor', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('roofvogel', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('wbc', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('fiets', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('hub', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('dvp', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('vrfg', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('vleermuis', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('zwaluw', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('vlinder', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('teunisbloempijlstaart', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('zangvogel', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('biggenkruid', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('schijfhoren', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_deleted_at'), 'users', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_table('activity_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=64), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('batch_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_logs_action'), 'activity_logs', ['action'], unique=False)
    op.create_index(op.f('ix_activity_logs_actor_id'), 'activity_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_activity_logs_batch_id'), 'activity_logs', ['batch_id'], unique=False)
    op.create_index(op.f('ix_activity_logs_target_id'), 'activity_logs', ['target_id'], unique=False)
    op.create_index(op.f('ix_activity_logs_target_type'), 'activity_logs', ['target_type'], unique=False)
    op.create_table('availability_weeks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('morning_days', sa.Integer(), nullable=False),
    sa.Column('daytime_days', sa.Integer(), nullable=False),
    sa.Column('nighttime_days', sa.Integer(), nullable=False),
    sa.Column('flex_days', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'week', name='uq_user_week')
    )
    op.create_index(op.f('ix_availability_weeks_deleted_at'), 'availability_weeks', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_availability_weeks_user_id'), 'availability_weeks', ['user_id'], unique=False)
    op.create_table('clusters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('cluster_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clusters_cluster_number'), 'clusters', ['cluster_number'], unique=False)
    op.create_index(op.f('ix_clusters_deleted_at'), 'clusters', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_clusters_project_id'), 'clusters', ['project_id'], unique=False)
    op.create_table('species',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('family_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('name_latin', sa.String(length=255), nullable=True),
    sa.Column('abbreviation', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_species_abbreviation'), 'species', ['abbreviation'], unique=False)
    op.create_index(op.f('ix_species_family_id'), 'species', ['family_id'], unique=False)
    op.create_index(op.f('ix_species_name'), 'species', ['name'], unique=True)
    op.create_index(op.f('ix_species_name_latin'), 'species', ['name_latin'], unique=True)
    op.create_table('protocols',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('species_id', sa.Integer(), nullable=False),
    sa.Column('function_id', sa.Integer(), nullable=False),
    sa.Column('visits', sa.Integer(), nullable=True),
    sa.Column('visit_duration_hours', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('min_period_between_visits_value', sa.Integer(), nullable=True),
    sa.Column('min_period_between_visits_unit', sa.String(length=32), nullable=True),
    sa.Column('start_timing_reference', sa.String(length=64), nullable=True),
    sa.Column('start_time_relative_minutes', sa.Integer(), nullable=True),
    sa.Column('start_time_absolute_from', sa.Time(), nullable=True),
    sa.Column('start_time_absolute_to', sa.Time(), nullable=True),
    sa.Column('end_timing_reference', sa.String(length=64), nullable=True),
    sa.Column('end_time_relative_minutes', sa.Integer(), nullable=True),
    sa.Column('min_temperature_celsius', sa.Integer(), nullable=True),
    sa.Column('max_wind_force_bft', sa.Integer(), nullable=True),
    sa.Column('max_precipitation', sa.String(length=64), nullable=True),
    sa.Column('start_time_condition', sa.String(length=255), nullable=True),
    sa.Column('end_time_condition', sa.String(length=255), nullable=True),
    sa.Column('visit_conditions_text', sa.String(length=1024), nullable=True),
    sa.Column('requires_morning_visit', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('requires_evening_visit', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('requires_june_visit', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('requires_maternity_period_visit', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('requires_july_visit', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['function_id'], ['functions.id'], ),
    sa.ForeignKeyConstraint(['species_id'], ['species.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_protocols_function_id'), 'protocols', ['function_id'], unique=False)
    op.create_index(op.f('ix_protocols_species_id'), 'protocols', ['species_id'], unique=False)
    op.create_table('visits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.String(length=64), nullable=True),
    sa.Column('schedule_group_id', sa.String(length=64), nullable=True),
    sa.Column('required_researchers', sa.Integer(), nullable=True),
    sa.Column('visit_nr', sa.Integer(), nullable=True),
    sa.Column('from', sa.Date(), nullable=True),
    sa.Column('to', sa.Date(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('min_temperature_celsius', sa.Integer(), nullable=True),
    sa.Column('max_wind_force_bft', sa.Integer(), nullable=True),
    sa.Column('max_precipitation', sa.String(length=64), nullable=True),
    sa.Column('expertise_level', sa.String(length=64), nullable=True),
    sa.Column('wbc', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('fiets', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('hub', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('dvp', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('sleutel', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('requires_morning_visit', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('requires_evening_visit', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('requires_june_visit', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('requires_maternity_period_visit', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('remarks_planning', sa.String(length=1024), nullable=True),
    sa.Column('remarks_field', sa.String(length=1024), nullable=True),
    sa.Column('priority', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('part_of_day', sa.String(length=16), nullable=True),
    sa.Column('start_time_text', sa.String(length=64), nullable=True),
    sa.Column('preferred_researcher_id', sa.Integer(), nullable=True),
    sa.Column('planned_week', sa.Integer(), nullable=True),
    sa.Column('advertized', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('quote', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ),
    sa.ForeignKeyConstraint(['preferred_researcher_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visits_cluster_id'), 'visits', ['cluster_id'], unique=False)
    op.create_index(op.f('ix_visits_deleted_at'), 'visits', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_visits_group_id'), 'visits', ['group_id'], unique=False)
    op.create_index(op.f('ix_visits_schedule_group_id'), 'visits', ['schedule_group_id'], unique=False)
    op.create_table('protocol_visit_windows',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('protocol_id', sa.Integer(), nullable=False),
    sa.Column('visit_index', sa.Integer(), nullable=False),
    sa.Column('window_from', sa.Date(), nullable=False),
    sa.Column('window_to', sa.Date(), nullable=False),
    sa.Column('required', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('label', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('window_from <= window_to', name='ck_window_range_valid'),
    sa.ForeignKeyConstraint(['protocol_id'], ['protocols.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('protocol_id', 'visit_index', name='uq_protocol_visit_idx')
    )
    op.create_index(op.f('ix_protocol_visit_windows_protocol_id'), 'protocol_visit_windows', ['protocol_id'], unique=False)
    op.create_table('visit_functions',
    sa.Column('visit_id', sa.Integer(), nullable=False),
    sa.Column('function_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['function_id'], ['functions.id'], ),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ),
    sa.PrimaryKeyConstraint('visit_id', 'function_id')
    )
    op.create_table('visit_researchers',
    sa.Column('visit_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ),
    sa.PrimaryKeyConstraint('visit_id', 'user_id')
    )
    op.create_table('visit_species',
    sa.Column('visit_id', sa.Integer(), nullable=False),
    sa.Column('species_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['species_id'], ['species.id'], ),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ),
    sa.PrimaryKeyConstraint('visit_id', 'species_id')
    )
    op.create_table('visit_protocol_visit_windows',
    sa.Column('visit_id', sa.Integer(), nullable=False),
    sa.Column('protocol_visit_window_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['protocol_visit_window_id'], ['protocol_visit_windows.id'], ),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ),
    sa.PrimaryKeyConstraint('visit_id', 'protocol_visit_window_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the upgrade migrations."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visit_protocol_visit_windows')
    op.drop_table('visit_species')
    op.drop_table('visit_researchers')
    op.drop_table('visit_functions')
    op.drop_index(op.f('ix_protocol_visit_windows_protocol_id'), table_name='protocol_visit_windows')
    op.drop_table('protocol_visit_windows')
    op.drop_index(op.f('ix_visits_schedule_group_id'), table_name='visits')
    op.drop_index(op.f('ix_visits_group_id'), table_name='visits')
    op.drop_index(op.f('ix_visits_deleted_at'), table_name='visits')
    op.drop_index(op.f('ix_visits_cluster_id'), table_name='visits')
    op.drop_table('visits')
    op.drop_index(op.f('ix_protocols_species_id'), table_name='protocols')
    op.drop_index(op.f('ix_protocols_function_id'), table_name='protocols')
    op.drop_table('protocols')
    op.drop_index(op.f('ix_species_name_latin'), table_name='species')
    op.drop_index(op.f('ix_species_name'), table_name='species')
    op.drop_index(op.f('ix_species_family_id'), table_name='species')
    op.drop_index(op.f('ix_species_abbreviation'), table_name='species')
    op.drop_table('species')
    op.drop_index(op.f('ix_clusters_project_id'), table_name='clusters')
    op.drop_index(op.f('ix_clusters_deleted_at'), table_name='clusters')
    op.drop_index(op.f('ix_clusters_cluster_number'), table_name='clusters')
    op.drop_table('clusters')
    op.drop_index(op.f('ix_availability_weeks_user_id'), table_name='availability_weeks')
    op.drop_index(op.f('ix_availability_weeks_deleted_at'), table_name='availability_weeks')
    op.drop_table('availability_weeks')
    op.drop_index(op.f('ix_activity_logs_target_type'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_target_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_batch_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_actor_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_action'), table_name='activity_logs')
    op.drop_table('activity_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_deleted_at'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_projects_deleted_at'), table_name='projects')
    op.drop_index(op.f('ix_projects_code'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_functions_name'), table_name='functions')
    op.drop_table('functions')
    op.drop_index(op.f('ix_families_name'), table_name='families')
    op.drop_table('families')
    # ### end Alembic commands ###
