"""add_unique_email_constraint_to_users

Revision ID: 2c4596e9fd0b
Revises: 20260130_02_refdata_updates
Create Date: 2026-02-05 16:49:05.920370

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c4596e9fd0b'
down_revision = '20260130_02_refdata_updates'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Apply the upgrade migrations."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Check for duplicates ONLY among active users (deleted_at IS NULL)
    op.execute("""
        UPDATE users
        SET email = CONCAT(email, '_duplicate_', id)
        WHERE id IN (
            SELECT id
            FROM (
                SELECT id,
                       ROW_NUMBER() OVER (PARTITION BY email ORDER BY id) as rnum
                FROM users
                WHERE deleted_at IS NULL
            ) t
            WHERE t.rnum > 1
        );
    """)

    # Create Partial Unique Index
    op.create_index(
        'ix_users_email_unique_active',
        'users',
        ['email'],
        unique=True,
        postgresql_where=sa.text('deleted_at IS NULL')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the upgrade migrations."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_email_unique_active', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    # ### end Alembic commands ###
