"""Add TravelTimeCache table

Revision ID: 40b411ecf4f5
Revises: 20260219_03
Create Date: 2026-02-21 21:43:03.727156

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40b411ecf4f5'
down_revision = '20260219_03'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Apply the upgrade migrations."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('travel_time_cache',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('origin', sa.String(length=255), nullable=False),
    sa.Column('destination', sa.String(length=255), nullable=False),
    sa.Column('travel_minutes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_travel_time_cache_destination'), 'travel_time_cache', ['destination'], unique=False)
    op.create_index(op.f('ix_travel_time_cache_origin'), 'travel_time_cache', ['origin'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the upgrade migrations."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_travel_time_cache_origin'), table_name='travel_time_cache')
    op.drop_index(op.f('ix_travel_time_cache_destination'), table_name='travel_time_cache')
    op.drop_table('travel_time_cache')
    # ### end Alembic commands ###
