"""Add language to users

Revision ID: 563734aa12e8
Revises: 9a9033459b0e
Create Date: 2026-02-15 23:01:40.030484

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '563734aa12e8'
down_revision = '9a9033459b0e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Apply the upgrade migrations."""
    # ### commands auto generated by Alembic - please adjust! ###
    language_enum = sa.Enum('EN', 'NL', name='language_type')
    language_enum.create(op.get_bind())
    op.add_column('users', sa.Column('language', language_enum, server_default='NL', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the upgrade migrations."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'language')
    sa.Enum(name='language_type').drop(op.get_bind())
    # ### end Alembic commands ###
