"""availability improvements

Revision ID: 5a70c3357ce5
Revises: e04e3e8d866c
Create Date: 2026-02-25 13:46:54.696903

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a70c3357ce5'
down_revision = 'e04e3e8d866c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Apply the upgrade migrations."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_unavailabilities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('morning', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('daytime', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('nighttime', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_unavailabilities_user_id'), 'user_unavailabilities', ['user_id'], unique=False)
    op.add_column('availability_patterns', sa.Column('max_mornings_per_week', sa.Integer(), server_default='2', nullable=True))
    op.add_column('availability_patterns', sa.Column('max_evenings_per_week', sa.Integer(), server_default='5', nullable=True))
    op.drop_column('availability_patterns', 'max_visits_per_week')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the upgrade migrations."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('availability_patterns', sa.Column('max_visits_per_week', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('availability_patterns', 'max_evenings_per_week')
    op.drop_column('availability_patterns', 'max_mornings_per_week')
    op.drop_index(op.f('ix_user_unavailabilities_user_id'), table_name='user_unavailabilities')
    op.drop_table('user_unavailabilities')
    # ### end Alembic commands ###
