"""make reset_password_token_expires_at timezone-aware

Revision ID: 5da6360634fb
Revises: 12bac7852fc7
Create Date: 2026-02-17 15:32:09.985626

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5da6360634fb'
down_revision = '12bac7852fc7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Apply the upgrade migrations."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'reset_password_token_expires_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the upgrade migrations."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'reset_password_token_expires_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    # ### end Alembic commands ###
