"""Add VOG flag to User and Visit

Revision ID: 60574d3151a2
Revises: a161f83680ff
Create Date: 2026-02-26 11:44:37.872155

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60574d3151a2'
down_revision = 'a161f83680ff'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Apply the upgrade migrations."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('vog', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('visits', sa.Column('vog', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the upgrade migrations."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('visits', 'vog')
    op.drop_column('users', 'vog')
    # ### end Alembic commands ###
