"""Add planned_date to visits

Revision ID: 7e85b56c5afc
Revises: 3f8e2b73056e
Create Date: 2026-02-13 16:20:39.737915

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e85b56c5afc'
down_revision = '3f8e2b73056e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Apply the upgrade migrations."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visits', sa.Column('planned_date', sa.Date(), nullable=True))
    op.create_index(op.f('ix_visits_planned_date'), 'visits', ['planned_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the upgrade migrations."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_visits_planned_date'), table_name='visits')
    op.drop_column('visits', 'planned_date')
    # ### end Alembic commands ###
