"""add_custom_visit_fields

Revision ID: 8de78c8d9ed2
Revises: 32228ac89e55
Create Date: 2026-01-20 18:14:13.626504

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8de78c8d9ed2'
down_revision = '32228ac89e55'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Apply the upgrade migrations."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visits', sa.Column('custom_function_name', sa.String(length=256), nullable=True))
    op.add_column('visits', sa.Column('custom_species_name', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the upgrade migrations."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('visits', 'custom_species_name')
    op.drop_column('visits', 'custom_function_name')
    # ### end Alembic commands ###
