"""Add deleted_at to availability_patterns

Revision ID: 9a9033459b0e
Revises: 96ed5f6ba63c
Create Date: 2026-02-15 21:03:30.780087

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a9033459b0e'
down_revision = '96ed5f6ba63c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Apply the upgrade migrations."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('availability_patterns', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_availability_patterns_deleted_at'), 'availability_patterns', ['deleted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the upgrade migrations."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_availability_patterns_deleted_at'), table_name='availability_patterns')
    op.drop_column('availability_patterns', 'deleted_at')
    # ### end Alembic commands ###
