"""Add SoftDeleteMixin to UserUnavailability

Revision ID: a161f83680ff
Revises: 5a70c3357ce5
Create Date: 2026-02-26 10:40:06.454519

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a161f83680ff'
down_revision = '5a70c3357ce5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Apply the upgrade migrations."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_unavailabilities', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_user_unavailabilities_deleted_at'), 'user_unavailabilities', ['deleted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the upgrade migrations."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_unavailabilities_deleted_at'), table_name='user_unavailabilities')
    op.drop_column('user_unavailabilities', 'deleted_at')
    # ### end Alembic commands ###
