"""Add ArchivableMixin to core models

Revision ID: e04e3e8d866c
Revises: 40b411ecf4f5
Create Date: 2026-02-24 17:18:37.808558

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e04e3e8d866c'
down_revision = '40b411ecf4f5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Apply the upgrade migrations."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clusters', sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False))
    op.create_index(op.f('ix_clusters_is_archived'), 'clusters', ['is_archived'], unique=False)
    op.add_column('projects', sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False))
    op.create_index(op.f('ix_projects_is_archived'), 'projects', ['is_archived'], unique=False)
    op.add_column('visits', sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False))
    op.create_index(op.f('ix_visits_is_archived'), 'visits', ['is_archived'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the upgrade migrations."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_visits_is_archived'), table_name='visits')
    op.drop_column('visits', 'is_archived')
    op.drop_index(op.f('ix_projects_is_archived'), table_name='projects')
    op.drop_column('projects', 'is_archived')
    op.drop_index(op.f('ix_clusters_is_archived'), table_name='clusters')
    op.drop_column('clusters', 'is_archived')
    # ### end Alembic commands ###
