-- Seed generated for Rugstreeppad (family Pad)
SET statement_timeout = 0;
INSERT INTO families (name, priority) VALUES ('Pad', 5) ON CONFLICT (name) DO NOTHING;
INSERT INTO species (family_id, name, name_latin) VALUES ((SELECT id FROM families WHERE name = 'Pad'), 'Rugstreeppad', NULL) ON CONFLICT (name) DO NOTHING;
INSERT INTO functions (name) VALUES ('luisterbezoek april') ON CONFLICT (name) DO NOTHING;
INSERT INTO protocols (species_id, function_id, period_from, period_to, visits, visit_duration_hours, min_period_between_visits_value, min_period_between_visits_unit, start_timing_reference, start_time_relative_minutes, start_time_absolute_from, start_time_absolute_to, end_timing_reference, end_time_relative_minutes, min_temperature_celsius, max_wind_force_bft, max_precipitation, start_time_condition, end_time_condition, visit_conditions_text, requires_morning_visit, requires_evening_visit, requires_june_visit, requires_maternity_period_visit, special_follow_up_action) VALUES ((SELECT s.id FROM species s JOIN families f ON s.family_id = f.id WHERE f.name = 'Pad' AND s.name = 'Rugstreeppad'), (SELECT id FROM functions WHERE name = 'luisterbezoek april'), '2000-04-15', '2000-04-30', 1, 2, NULL, NULL, 'SUNSET', 60, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'relatief warme avonden, bij voorkeur na regen of een weersomslag', false, false, false, false, NULL) ON CONFLICT DO NOTHING;
INSERT INTO functions (name) VALUES ('luisterbezoek mei') ON CONFLICT (name) DO NOTHING;
INSERT INTO protocols (species_id, function_id, period_from, period_to, visits, visit_duration_hours, min_period_between_visits_value, min_period_between_visits_unit, start_timing_reference, start_time_relative_minutes, start_time_absolute_from, start_time_absolute_to, end_timing_reference, end_time_relative_minutes, min_temperature_celsius, max_wind_force_bft, max_precipitation, start_time_condition, end_time_condition, visit_conditions_text, requires_morning_visit, requires_evening_visit, requires_june_visit, requires_maternity_period_visit, special_follow_up_action) VALUES ((SELECT s.id FROM species s JOIN families f ON s.family_id = f.id WHERE f.name = 'Pad' AND s.name = 'Rugstreeppad'), (SELECT id FROM functions WHERE name = 'luisterbezoek mei'), '2000-05-15', '2000-05-31', 1, 2, NULL, NULL, 'SUNSET', 60, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'relatief warme avonden, bij voorkeur na regen of een weersomslag', false, false, false, false, NULL) ON CONFLICT DO NOTHING;
INSERT INTO functions (name) VALUES ('luisterbezoek juni/juli') ON CONFLICT (name) DO NOTHING;
INSERT INTO protocols (species_id, function_id, period_from, period_to, visits, visit_duration_hours, min_period_between_visits_value, min_period_between_visits_unit, start_timing_reference, start_time_relative_minutes, start_time_absolute_from, start_time_absolute_to, end_timing_reference, end_time_relative_minutes, min_temperature_celsius, max_wind_force_bft, max_precipitation, start_time_condition, end_time_condition, visit_conditions_text, requires_morning_visit, requires_evening_visit, requires_june_visit, requires_maternity_period_visit, special_follow_up_action) VALUES ((SELECT s.id FROM species s JOIN families f ON s.family_id = f.id WHERE f.name = 'Pad' AND s.name = 'Rugstreeppad'), (SELECT id FROM functions WHERE name = 'luisterbezoek juni/juli'), '2000-06-01', '2000-07-31', 1, 2, 7, 'days', 'SUNSET', 60, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'relatief warme avonden, bij voorkeur na regen of een weersomslag', false, false, false, false, NULL) ON CONFLICT DO NOTHING;
INSERT INTO functions (name) VALUES ('eisnoeren/larven + platen neerleggen') ON CONFLICT (name) DO NOTHING;
INSERT INTO protocols (species_id, function_id, period_from, period_to, visits, visit_duration_hours, min_period_between_visits_value, min_period_between_visits_unit, start_timing_reference, start_time_relative_minutes, start_time_absolute_from, start_time_absolute_to, end_timing_reference, end_time_relative_minutes, min_temperature_celsius, max_wind_force_bft, max_precipitation, start_time_condition, end_time_condition, visit_conditions_text, requires_morning_visit, requires_evening_visit, requires_june_visit, requires_maternity_period_visit, special_follow_up_action) VALUES ((SELECT s.id FROM species s JOIN families f ON s.family_id = f.id WHERE f.name = 'Pad' AND s.name = 'Rugstreeppad'), (SELECT id FROM functions WHERE name = 'eisnoeren/larven + platen neerleggen'), '2000-06-01', '2000-07-31', 1, 2, 7, 'days', 'SUNSET', 120, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, false, false, false, NULL) ON CONFLICT DO NOTHING;
INSERT INTO functions (name) VALUES ('platen controleren, landhabitat') ON CONFLICT (name) DO NOTHING;
INSERT INTO protocols (species_id, function_id, period_from, period_to, visits, visit_duration_hours, min_period_between_visits_value, min_period_between_visits_unit, start_timing_reference, start_time_relative_minutes, start_time_absolute_from, start_time_absolute_to, end_timing_reference, end_time_relative_minutes, min_temperature_celsius, max_wind_force_bft, max_precipitation, start_time_condition, end_time_condition, visit_conditions_text, requires_morning_visit, requires_evening_visit, requires_june_visit, requires_maternity_period_visit, special_follow_up_action) VALUES ((SELECT s.id FROM species s JOIN families f ON s.family_id = f.id WHERE f.name = 'Pad' AND s.name = 'Rugstreeppad'), (SELECT id FROM functions WHERE name = 'platen controleren, landhabitat'), '2000-07-01', '2000-08-31', 4, 3, 7, 'days', 'SUNSET', 60, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'relatief warme avonden, bij voorkeur na regen of een weersomslag', false, false, false, false, NULL) ON CONFLICT DO NOTHING;
