-- Seed generated for Gierzwaluw (family Zwaluw)
SET statement_timeout = 0;
INSERT INTO families (name, priority) VALUES ('Zwaluw', 5) ON CONFLICT (name) DO NOTHING;
INSERT INTO species (family_id, name, abbreviation) VALUES ((SELECT id FROM families WHERE name = 'Zwaluw'), 'Gierzwaluw', 'GZ') ON CONFLICT (name) DO NOTHING;
INSERT INTO functions (name) VALUES ('Nest') ON CONFLICT (name) DO NOTHING;
INSERT INTO functions (name) VALUES ('SMP Voorverkenning') ON CONFLICT (name) DO NOTHING;
INSERT INTO functions (name) VALUES ('SMP Nest') ON CONFLICT (name) DO NOTHING;
INSERT INTO protocols (species_id, function_id, visits, visit_duration_hours, min_period_between_visits_value, min_period_between_visits_unit, start_timing_reference, start_time_relative_minutes, start_time_absolute_from, start_time_absolute_to, end_timing_reference, end_time_relative_minutes, min_temperature_celsius, max_wind_force_bft, max_precipitation, start_time_condition, end_time_condition, visit_conditions_text, requires_morning_visit, requires_evening_visit, requires_june_visit, requires_maternity_period_visit) VALUES ((SELECT s.id FROM species s JOIN families f ON s.family_id = f.id WHERE f.name = 'Zwaluw' AND s.name = 'Gierzwaluw'), (SELECT id FROM functions WHERE name = 'Nest'), 3, 2, 10, 'dagen', 'SUNSET', -90, NULL, NULL, NULL, NULL, 13, 4, 'droog', NULL, NULL, NULL, false, false, false, false);
INSERT INTO protocol_visit_windows (protocol_id, visit_index, window_from, window_to, required, label)
SELECT p.id, v.visit_index, v.window_from, v.window_to, v.required, v.label
FROM (VALUES
  (1, DATE '2000-06-01', DATE '2000-06-15', true, NULL),
  (2, DATE '2000-06-15', DATE '2000-06-30', true, NULL),
  (3, DATE '2000-07-01', DATE '2000-07-15', true, NULL)
) AS v(visit_index, window_from, window_to, required, label),
LATERAL (SELECT id FROM protocols WHERE species_id = (SELECT s.id FROM species s JOIN families f ON s.family_id = f.id WHERE f.name = 'Zwaluw' AND s.name = 'Gierzwaluw') AND function_id = (SELECT id FROM functions WHERE name = 'Nest') ORDER BY id DESC LIMIT 1) AS p(id);
INSERT INTO species (family_id, name, name_latin) VALUES ((SELECT id FROM families WHERE name = 'Zwaluw'), 'Gierzwaluw', NULL) ON CONFLICT (name) DO NOTHING;
INSERT INTO protocols (species_id, function_id, visits, visit_duration_hours, min_period_between_visits_value, min_period_between_visits_unit, start_timing_reference, start_time_relative_minutes, start_time_absolute_from, start_time_absolute_to, end_timing_reference, end_time_relative_minutes, min_temperature_celsius, max_wind_force_bft, max_precipitation, start_time_condition, end_time_condition, visit_conditions_text, requires_morning_visit, requires_evening_visit, requires_june_visit, requires_maternity_period_visit) VALUES ((SELECT s.id FROM species s JOIN families f ON s.family_id = f.id WHERE f.name = 'Zwaluw' AND s.name = 'Gierzwaluw'), (SELECT id FROM functions WHERE name = 'SMP Voorverkenning'), 1, 2, NULL, NULL, 'SUNSET', -90, NULL, NULL, NULL, NULL, NULL, 4, 'droog', 'Temperatuur afhankelijk per week', NULL, NULL, false, false, false, false);
INSERT INTO protocol_visit_windows (protocol_id, visit_index, window_from, window_to, required, label)
SELECT p.id, 1, DATE '2000-05-25', DATE '2000-05-31', true, NULL
FROM LATERAL (SELECT id FROM protocols WHERE species_id = (SELECT s.id FROM species s JOIN families f ON s.family_id = f.id WHERE f.name = 'Zwaluw' AND s.name = 'Gierzwaluw') AND function_id = (SELECT id FROM functions WHERE name = 'SMP Voorverkenning') ORDER BY id DESC LIMIT 1) AS p(id);
INSERT INTO species (family_id, name, name_latin) VALUES ((SELECT id FROM families WHERE name = 'Zwaluw'), 'Huiszwaluw', NULL) ON CONFLICT (name) DO NOTHING;
INSERT INTO protocols (species_id, function_id, visits, visit_duration_hours, min_period_between_visits_value, min_period_between_visits_unit, start_timing_reference, start_time_relative_minutes, start_time_absolute_from, start_time_absolute_to, end_timing_reference, end_time_relative_minutes, min_temperature_celsius, max_wind_force_bft, max_precipitation, start_time_condition, end_time_condition, visit_conditions_text, requires_morning_visit, requires_evening_visit, requires_june_visit, requires_maternity_period_visit) VALUES ((SELECT s.id FROM species s JOIN families f ON s.family_id = f.id WHERE f.name = 'Zwaluw' AND s.name = 'Huiszwaluw'), (SELECT id FROM functions WHERE name = 'SMP Voorverkenning'), 1, 2, NULL, NULL, 'SUNSET', -90, NULL, NULL, NULL, NULL, NULL, 4, 'droog', 'Temperatuur afhankelijk per week', NULL, NULL, false, false, false, false);
INSERT INTO protocol_visit_windows (protocol_id, visit_index, window_from, window_to, required, label)
SELECT p.id, 1, DATE '2000-05-25', DATE '2000-05-31', true, NULL
FROM LATERAL (SELECT id FROM protocols WHERE species_id = (SELECT s.id FROM species s JOIN families f ON s.family_id = f.id WHERE f.name = 'Zwaluw' AND s.name = 'Huiszwaluw') AND function_id = (SELECT id FROM functions WHERE name = 'SMP Voorverkenning') ORDER BY id DESC LIMIT 1) AS p(id);
INSERT INTO species (family_id, name, name_latin) VALUES ((SELECT id FROM families WHERE name = 'Zwaluw'), 'Boerenzwaluw', NULL) ON CONFLICT (name) DO NOTHING;
INSERT INTO protocols (species_id, function_id, visits, visit_duration_hours, min_period_between_visits_value, min_period_between_visits_unit, start_timing_reference, start_time_relative_minutes, start_time_absolute_from, start_time_absolute_to, end_timing_reference, end_time_relative_minutes, min_temperature_celsius, max_wind_force_bft, max_precipitation, start_time_condition, end_time_condition, visit_conditions_text, requires_morning_visit, requires_evening_visit, requires_june_visit, requires_maternity_period_visit) VALUES ((SELECT s.id FROM species s JOIN families f ON s.family_id = f.id WHERE f.name = 'Zwaluw' AND s.name = 'Boerenzwaluw'), (SELECT id FROM functions WHERE name = 'SMP Voorverkenning'), 1, 2, NULL, NULL, 'SUNSET', -90, NULL, NULL, NULL, NULL, NULL, 4, 'droog', 'Temperatuur afhankelijk per week', NULL, NULL, false, false, false, false);
INSERT INTO protocol_visit_windows (protocol_id, visit_index, window_from, window_to, required, label)
SELECT p.id, 1, DATE '2000-05-25', DATE '2000-05-31', true, NULL
FROM LATERAL (SELECT id FROM protocols WHERE species_id = (SELECT s.id FROM species s JOIN families f ON s.family_id = f.id WHERE f.name = 'Zwaluw' AND s.name = 'Boerenzwaluw') AND function_id = (SELECT id FROM functions WHERE name = 'SMP Voorverkenning') ORDER BY id DESC LIMIT 1) AS p(id);
INSERT INTO protocols (species_id, function_id, visits, visit_duration_hours, min_period_between_visits_value, min_period_between_visits_unit, start_timing_reference, start_time_relative_minutes, start_time_absolute_from, start_time_absolute_to, end_timing_reference, end_time_relative_minutes, min_temperature_celsius, max_wind_force_bft, max_precipitation, start_time_condition, end_time_condition, visit_conditions_text, requires_morning_visit, requires_evening_visit, requires_june_visit, requires_maternity_period_visit) VALUES ((SELECT s.id FROM species s JOIN families f ON s.family_id = f.id WHERE f.name = 'Zwaluw' AND s.name = 'Gierzwaluw'), (SELECT id FROM functions WHERE name = 'SMP Nest'), 2, 2, 10, 'dagen', 'SUNSET', -90, NULL, NULL, NULL, NULL, NULL, 4, 'droog', 'Temperatuur afhankelijk per week', NULL, NULL, false, false, false, false);
INSERT INTO protocol_visit_windows (protocol_id, visit_index, window_from, window_to, required, label)
SELECT p.id, v.visit_index, v.window_from, v.window_to, v.required, v.label
FROM (VALUES
  (1, DATE '2000-06-08', DATE '2000-06-30', true, NULL),
  (2, DATE '2000-07-01', DATE '2000-07-15', true, NULL)
) AS v(visit_index, window_from, window_to, required, label),
LATERAL (SELECT id FROM protocols WHERE species_id = (SELECT s.id FROM species s JOIN families f ON s.family_id = f.id WHERE f.name = 'Zwaluw' AND s.name = 'Gierzwaluw') AND function_id = (SELECT id FROM functions WHERE name = 'SMP Nest') ORDER BY id DESC LIMIT 1) AS p(id);
